#!/bin/bash
# Build WASM module for Rource

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
WASM_DIR="$PROJECT_ROOT/rource-wasm"

echo "=== Building Rource WASM ==="
echo ""

# Check for wasm-pack
if ! command -v wasm-pack &> /dev/null; then
    echo "Error: wasm-pack not found. Install with: cargo install wasm-pack"
    exit 1
fi

cd "$WASM_DIR"

# Build with wasm-pack
echo "Building WASM with wasm-pack..."
wasm-pack build --target web --release

# Copy to www directory
echo "Copying package to www directory..."
cp -r pkg www/

# Optimize with wasm-opt if available
if command -v wasm-opt &> /dev/null; then
    echo "Optimizing with wasm-opt..."
    wasm-opt -Oz -o www/pkg/rource_wasm_bg_opt.wasm www/pkg/rource_wasm_bg.wasm
    mv www/pkg/rource_wasm_bg_opt.wasm www/pkg/rource_wasm_bg.wasm
    echo "WASM optimized"
else
    echo "Note: wasm-opt not found (optional - install via binaryen for smaller output)"
fi

# Print output sizes
echo ""
echo "=== Build Complete ==="
echo ""
echo "Output files in: $WASM_DIR/www/pkg/"
ls -lh www/pkg/*.wasm www/pkg/*.js 2>/dev/null || true

# Print gzip size estimate and generate build-info.js
if command -v gzip &> /dev/null; then
    echo ""
    echo "Gzip sizes:"
    WASM_GZIP_KB=0
    for f in www/pkg/*.wasm; do
        if [ -f "$f" ]; then
            gzip_size=$(gzip -c "$f" | wc -c)
            WASM_GZIP_KB=$((gzip_size / 1024))
            echo "  $(basename "$f"): $(numfmt --to=iec $gzip_size 2>/dev/null || echo "$gzip_size bytes")"
        fi
    done

    # Generate build-info.js with actual sizes and stats
    JS_GZIP_SIZE=$(gzip -c www/pkg/rource_wasm.js 2>/dev/null | wc -c || echo 0)
    JS_GZIP_KB=$((JS_GZIP_SIZE / 1024))
    BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    CRATE_COUNT=$(ls -d "$PROJECT_ROOT/crates"/*/ 2>/dev/null | wc -l)

    # Test count - expensive to calculate, so we use a static value
    # Update manually by running: cargo test --all 2>&1 | grep -E "^test result:" | awk '{sum += $4} END {print sum}'
    TEST_COUNT=903

    echo ""
    echo "Generating www/js/build-info.js..."
    cat > www/js/build-info.js << EOF
// Auto-generated by build-wasm.sh - do not edit manually
// Test count is static; update by running: cargo test --all 2>&1 | grep "^test result:" | awk '{sum += \$4} END {print sum}'
export const BUILD_INFO = {
    wasmGzipKB: ${WASM_GZIP_KB},
    jsGzipKB: ${JS_GZIP_KB},
    crateCount: ${CRATE_COUNT},
    testCount: ${TEST_COUNT},
    buildDate: '${BUILD_DATE}'
};
EOF
    echo "  WASM gzipped: ~${WASM_GZIP_KB}KB"
    echo "  Crates: ${CRATE_COUNT}"
fi

echo ""
echo "To serve the demo:"
echo "  cd $WASM_DIR/www && python3 -m http.server 8080"
echo "  Then open http://localhost:8080"
