#!/bin/bash
# Build optimized web assets for Rource WASM demo
# Bundles JS modules and optimizes CSS loading

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
WWW_DIR="$PROJECT_ROOT/rource-wasm/www"
JS_DIR="$WWW_DIR/js"
DIST_DIR="$WWW_DIR/dist"

echo "=== Building Optimized Web Assets ==="
echo ""

# Create dist directory
mkdir -p "$DIST_DIR"

# ============================================================
# Bundle JavaScript modules
# ============================================================
echo "Bundling JavaScript modules..."

# The bundle order matters - dependencies must come before dependents
# This is a topologically sorted list based on import analysis
JS_MODULES=(
    "config.js"
    "telemetry.js"
    "utils.js"
    "state.js"
    "dom.js"
    "preferences.js"
    "url-state.js"
    "wasm-api.js"
    "cached-data.js"
    "toast.js"
    "animation.js"
    "data-loader.js"
    "github-fetch.js"
    "build-info.js"
    "features/playback.js"
    "features/canvas-input.js"
    "features/panels.js"
    "features/data-input.js"
    "features/window-events.js"
    "features/screenshot.js"
    "features/fullscreen.js"
    "features/theme.js"
    "features/help.js"
    "features/keyboard.js"
    "features/full-map-export.js"
    "features/font-size.js"
    "features/video-recording.js"
    "main.js"
)

# Create bundled JS file
BUNDLE_FILE="$DIST_DIR/rource-bundle.js"
echo "// Rource - Bundled JavaScript" > "$BUNDLE_FILE"
echo "// Auto-generated by build-web.sh - do not edit manually" >> "$BUNDLE_FILE"
echo "// Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$BUNDLE_FILE"
echo "" >> "$BUNDLE_FILE"

# Create module wrapper to handle ES module syntax
cat >> "$BUNDLE_FILE" << 'BUNDLE_HEADER'
(function() {
'use strict';

// Module registry for ES module emulation
const __modules = {};
const __exports = {};

function __define(name, factory) {
    __modules[name] = factory;
}

function __require(name) {
    if (!__exports[name]) {
        __exports[name] = {};
        if (__modules[name]) {
            __modules[name](__exports[name]);
        }
    }
    return __exports[name];
}

// WASM module - loaded separately and injected
let __wasmInit, __wasmRource;

BUNDLE_HEADER

# Process each module
for module in "${JS_MODULES[@]}"; do
    module_path="$JS_DIR/$module"
    if [ ! -f "$module_path" ]; then
        echo "Warning: Module not found: $module"
        continue
    fi

    # Convert path to module name (e.g., "features/playback.js" -> "features/playback")
    module_name="${module%.js}"

    echo "  Adding: $module"

    # Start module definition
    echo "" >> "$BUNDLE_FILE"
    echo "// ======== Module: $module_name ========" >> "$BUNDLE_FILE"
    echo "__define('$module_name', function(__exports) {" >> "$BUNDLE_FILE"

    # Process the module content:
    # 1. Convert export statements to __exports assignments
    # 2. Convert import statements to __require calls
    # 3. Handle the WASM import specially
    cat "$module_path" | \
        # Remove the WASM import (handled separately)
        sed "s|import init, { Rource } from '../pkg/rource_wasm.js';|const init = __wasmInit; const Rource = __wasmRource;|g" | \
        # Convert named imports: import { foo, bar } from './module.js'
        sed -E "s|import \{([^}]+)\} from '\.\.?/([^']+)\.js';|const {\1} = __require('\2');|g" | \
        sed -E "s|import \{([^}]+)\} from '\.\.?/([^']+)';|const {\1} = __require('\2');|g" | \
        # Convert named exports: export function foo() -> __exports.foo = function foo()
        sed -E "s|^export function ([a-zA-Z_][a-zA-Z0-9_]*)|__exports.\1 = function \1|g" | \
        # Convert const/let/var exports: export const foo = -> __exports.foo =
        sed -E "s|^export (const\|let\|var) ([a-zA-Z_][a-zA-Z0-9_]*) =|__exports.\2 =|g" | \
        # Convert class exports: export class Foo -> __exports.Foo = class Foo
        sed -E "s|^export class ([a-zA-Z_][a-zA-Z0-9_]*)|__exports.\1 = class \1|g" | \
        # Convert default exports (not used in this codebase, but handle it)
        sed -E "s|^export default|__exports.default =|g" \
        >> "$BUNDLE_FILE"

    echo "" >> "$BUNDLE_FILE"
    echo "});" >> "$BUNDLE_FILE"
done

# Add bundle footer with initialization
cat >> "$BUNDLE_FILE" << 'BUNDLE_FOOTER'

// ======== Bundle Initialization ========
async function __initBundle() {
    // Load WASM module
    const wasmModule = await import('./pkg/rource_wasm.js');
    __wasmInit = wasmModule.default;
    __wasmRource = wasmModule.Rource;

    // Initialize all modules in order (this triggers their side effects)
    __require('config');
    __require('telemetry');
    __require('utils');
    __require('state');
    __require('dom');
    __require('preferences');
    __require('url-state');
    __require('wasm-api');
    __require('cached-data');
    __require('toast');
    __require('animation');
    __require('data-loader');
    __require('github-fetch');
    __require('build-info');
    __require('features/playback');
    __require('features/canvas-input');
    __require('features/panels');
    __require('features/data-input');
    __require('features/window-events');
    __require('features/screenshot');
    __require('features/fullscreen');
    __require('features/theme');
    __require('features/help');
    __require('features/keyboard');
    __require('features/full-map-export');
    __require('features/font-size');
    __require('features/video-recording');
    __require('main');
}

__initBundle().catch(console.error);

})();
BUNDLE_FOOTER

echo "  Bundle created: $BUNDLE_FILE"

# Get bundle size
BUNDLE_SIZE=$(wc -c < "$BUNDLE_FILE")
echo "  Bundle size: $(numfmt --to=iec $BUNDLE_SIZE 2>/dev/null || echo "$BUNDLE_SIZE bytes")"

# ============================================================
# Minify JavaScript (if terser is available)
# ============================================================
if command -v terser &> /dev/null; then
    echo ""
    echo "Minifying JavaScript with terser..."
    terser "$BUNDLE_FILE" -o "$DIST_DIR/rource-bundle.min.js" -c -m
    MIN_SIZE=$(wc -c < "$DIST_DIR/rource-bundle.min.js")
    echo "  Minified size: $(numfmt --to=iec $MIN_SIZE 2>/dev/null || echo "$MIN_SIZE bytes")"
else
    echo ""
    echo "Note: terser not found - skipping minification"
    echo "      Install with: npm install -g terser"
    cp "$BUNDLE_FILE" "$DIST_DIR/rource-bundle.min.js"
fi

# ============================================================
# Extract Critical CSS
# ============================================================
echo ""
echo "Extracting critical CSS..."

# Critical CSS includes: CSS variables, loading skeleton, header, main layout
# This is enough to render the initial view without FOUC
CRITICAL_CSS="$DIST_DIR/critical.css"

cat > "$CRITICAL_CSS" << 'CRITICAL_END'
/* Critical CSS - Inline for fast initial render */
*{margin:0;padding:0;box-sizing:border-box}
:root{--bg-primary:#0d1117;--bg-secondary:#161b22;--bg-tertiary:#21262d;--bg-canvas:#010409;--accent:#e94560;--accent-hover:#ff6b6b;--accent-secondary:#238636;--accent-blue:#58a6ff;--text-primary:#f0f6fc;--text-secondary:#8b949e;--text-muted:#6e7681;--border:#30363d;--border-light:#484f58;--success:#3fb950;--error:#f85149;--warning:#d29922;--shadow:rgba(0,0,0,0.4);--spacing-xs:0.25rem;--spacing-sm:0.5rem;--spacing-md:0.75rem;--spacing-lg:1rem;--spacing-xl:1.5rem;--radius-sm:4px;--radius-md:6px;--radius-lg:8px;--radius-xl:12px;--radius-full:9999px;--transition-fast:0.15s;--transition-normal:0.2s;--transition-slow:0.3s}
html,body{height:100%;overflow:hidden}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','Noto Sans',Helvetica,Arial,sans-serif;background:var(--bg-primary);color:var(--text-primary);line-height:1.5;display:flex;flex-direction:column}
:focus-visible{outline:2px solid var(--accent-blue);outline-offset:2px}
a{color:var(--accent-blue);text-decoration:none}
.skip-link{position:absolute;top:-40px;left:0;background:var(--accent);color:white;padding:8px 16px;z-index:1000;text-decoration:none;border-radius:0 0 4px 0}
.skip-link:focus{top:0}
header{background:var(--bg-secondary);padding:0.75rem 1.5rem;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--border);flex-wrap:wrap;gap:0.75rem;flex-shrink:0;z-index:100}
.header-brand{display:flex;align-items:center;gap:0.75rem}
.header-brand a{display:flex;align-items:center;gap:0.5rem;text-decoration:none;color:var(--text-primary)}
.logo-icon{width:28px;height:28px}
header h1{font-size:1.25rem;font-weight:600;background:linear-gradient(135deg,var(--accent) 0%,#ff9a9e 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
.controls{display:flex;gap:0.5rem;align-items:center;flex-wrap:wrap}
#loading{position:fixed;inset:0;background:var(--bg-primary);display:flex;align-items:center;justify-content:center;z-index:1000;flex-direction:column}
#loading.hidden{display:none}
.loading-skeleton{position:absolute;inset:0;opacity:0.3}
.skeleton-header{height:60px;background:var(--bg-secondary);display:flex;align-items:center;padding:0 1.5rem;gap:1rem}
.skeleton-bar{background:var(--bg-tertiary);border-radius:4px}
.skeleton-logo{width:28px;height:28px;border-radius:50%}
.skeleton-title{width:100px;height:24px}
.skeleton-buttons{display:flex;gap:0.5rem;margin-left:auto}
.skeleton-btn{width:80px;height:32px}
.skeleton-body{display:flex;height:calc(100% - 60px)}
.skeleton-canvas{flex:1;background:var(--bg-canvas);display:flex;align-items:center;justify-content:center}
.skeleton-viz{position:relative;width:200px;height:200px}
.skeleton-node{position:absolute;border-radius:50%;background:var(--bg-tertiary)}
.skeleton-node-1{width:40px;height:40px;top:20%;left:40%}
.skeleton-node-2{width:24px;height:24px;top:50%;left:25%}
.skeleton-node-3{width:24px;height:24px;top:50%;left:65%}
.skeleton-node-4{width:20px;height:20px;top:75%;left:45%}
.skeleton-beam{position:absolute;height:2px;background:var(--accent);opacity:0.3;transform-origin:left center}
.skeleton-beam-1{width:60px;top:35%;left:45%;transform:rotate(35deg)}
.skeleton-beam-2{width:50px;top:55%;left:35%;transform:rotate(-25deg)}
.skeleton-sidebar{width:320px;background:var(--bg-secondary);padding:1rem;border-left:1px solid var(--border);display:flex;flex-direction:column;gap:0.75rem}
.skeleton-panel{height:120px}
.skeleton-panel-sm{height:60px}
.loading-content{position:relative;z-index:1;text-align:center}
.loading-spinner{width:48px;height:48px;border:3px solid var(--border);border-top-color:var(--accent);border-radius:50%;animation:spin 1s linear infinite;margin:0 auto 1rem}
@keyframes spin{to{transform:rotate(360deg)}}
.loading-text{font-size:1.25rem;color:var(--text-primary);margin-bottom:0.5rem}
.loading-subtext{font-size:0.875rem;color:var(--text-secondary)}
.app-container{flex:1;display:flex;overflow:hidden}
.viz-panel{flex:1;display:flex;flex-direction:column;background:var(--bg-canvas);min-width:0}
#canvas-container{flex:1;position:relative;overflow:hidden}
canvas{width:100%;height:100%;display:block}
.sidebar-wrapper{width:320px;display:flex;flex-direction:column;background:var(--bg-secondary);border-left:1px solid var(--border)}
.sidebar-panel{flex:1;overflow-y:auto;padding:1rem}
@media(max-width:768px){.sidebar-wrapper{position:fixed;right:-100%;width:85%;max-width:360px;height:100%;z-index:200;transition:right 0.3s ease}.controls{display:none}}
CRITICAL_END

echo "  Critical CSS extracted: $CRITICAL_CSS"
CRITICAL_SIZE=$(wc -c < "$CRITICAL_CSS")
echo "  Critical CSS size: $(numfmt --to=iec $CRITICAL_SIZE 2>/dev/null || echo "$CRITICAL_SIZE bytes")"

# ============================================================
# Create optimized index.html
# ============================================================
echo ""
echo "Creating optimized index.html..."

# Read critical CSS content for inlining
CRITICAL_CSS_CONTENT=$(cat "$CRITICAL_CSS")

# Create the optimized HTML file
cat > "$DIST_DIR/index.html" << 'HTML_HEAD'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
    <title>Rource - Software Version Control Visualization</title>
    <meta name="description" content="Visualize your git repository history as an animated tree. Watch your codebase grow as developers collaborate. Runs in your browser with WebAssembly.">
    <meta name="keywords" content="git, visualization, gource, repository, version control, wasm, webassembly, rust">
    <meta name="author" content="Rource Contributors">

    <!-- Open Graph / Social Sharing -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://tomtom215.github.io/rource/">
    <meta property="og:title" content="Rource - Software Version Control Visualization">
    <meta property="og:description" content="Visualize your git repository history as an animated tree. Watch your codebase grow as developers collaborate.">
    <meta property="og:image" content="https://tomtom215.github.io/rource/og-image.png">

    <!-- Twitter Card -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Rource - Software Version Control Visualization">
    <meta name="twitter:description" content="Visualize your git repository history as an animated tree. Runs entirely in your browser.">

    <!-- Favicon (inline SVG as data URI) -->
    <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><circle cx='50' cy='50' r='45' fill='%23e94560'/><circle cx='50' cy='30' r='8' fill='white'/><circle cx='30' cy='60' r='6' fill='white'/><circle cx='70' cy='55' r='6' fill='white'/><circle cx='50' cy='75' r='5' fill='white'/><line x1='50' y1='38' x2='50' y2='70' stroke='white' stroke-width='2'/><line x1='50' y1='50' x2='32' y2='58' stroke='white' stroke-width='2'/><line x1='50' y1='50' x2='68' y2='53' stroke='white' stroke-width='2'/></svg>">

    <!-- Theme color for mobile browsers -->
    <meta name="theme-color" content="#1a1a2e">

    <!-- Preload critical resources -->
    <link rel="preload" href="pkg/rource_wasm_bg.wasm" as="fetch" crossorigin>

    <!-- Critical CSS (inlined for fast initial render) -->
    <style>
HTML_HEAD

# Append critical CSS
echo "$CRITICAL_CSS_CONTENT" >> "$DIST_DIR/index.html"

cat >> "$DIST_DIR/index.html" << 'HTML_MIDDLE'
    </style>

    <!-- Full CSS (loaded asynchronously) -->
    <link rel="preload" href="styles.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="styles.css"></noscript>
</head>
HTML_MIDDLE

# Copy the body content from original index.html (everything from <body> to </html>)
# For now, we'll just reference the original and note that we need to copy body content
echo "  Note: Copy body content from original index.html to complete the optimized version"

# Actually, let's extract and append the body content
BODY_START=$(grep -n '<body>' "$WWW_DIR/index.html" | cut -d: -f1)
BODY_END=$(grep -n '</html>' "$WWW_DIR/index.html" | cut -d: -f1)

if [ -n "$BODY_START" ] && [ -n "$BODY_END" ]; then
    # Extract body content, but replace the script tag
    sed -n "${BODY_START},${BODY_END}p" "$WWW_DIR/index.html" | \
        sed 's|<script type="module" src="js/main.js"></script>|<script type="module" src="rource-bundle.min.js"></script>|' \
        >> "$DIST_DIR/index.html"
fi

echo "  Optimized index.html created: $DIST_DIR/index.html"

# ============================================================
# Copy required files to dist
# ============================================================
echo ""
echo "Copying additional files..."

# Copy styles.css
cp "$WWW_DIR/styles.css" "$DIST_DIR/"

# Copy pkg directory (WASM files)
if [ -d "$WWW_DIR/pkg" ]; then
    cp -r "$WWW_DIR/pkg" "$DIST_DIR/"
    echo "  Copied: pkg/ (WASM files)"
fi

# ============================================================
# Summary
# ============================================================
echo ""
echo "=== Build Complete ==="
echo ""
echo "Output directory: $DIST_DIR"
echo ""
echo "Files created:"
ls -lh "$DIST_DIR"/*.html "$DIST_DIR"/*.js "$DIST_DIR"/*.css 2>/dev/null | awk '{print "  " $NF ": " $5}'

# Calculate total size
if [ -d "$DIST_DIR" ]; then
    TOTAL_SIZE=$(du -sh "$DIST_DIR" 2>/dev/null | cut -f1)
    echo ""
    echo "Total dist size: $TOTAL_SIZE"
fi

echo ""
echo "To serve the optimized demo:"
echo "  cd $DIST_DIR && python3 -m http.server 8080"
echo "  Then open http://localhost:8080"
