#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Tom F <https://github.com/tomtom215>

# Build WASM module for Rource

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
WASM_DIR="$PROJECT_ROOT/rource-wasm"

echo "=== Building Rource WASM ==="
echo ""

# Check for wasm-pack
if ! command -v wasm-pack &> /dev/null; then
    echo "Error: wasm-pack not found. Install with: cargo install wasm-pack"
    exit 1
fi

cd "$WASM_DIR"

# Build with wasm-pack
echo "Building WASM with wasm-pack..."
wasm-pack build --target web --release

# Copy to www directory
echo "Copying package to www directory..."
cp -r pkg www/

# Optimize with wasm-opt if available
# Flags explained:
#   -O3: Maximum performance optimization (vs -Oz for size)
#   --converge: Iterate optimization passes until no further improvement
#   --low-memory-unused: Enable load/store offset folding for addresses <1024
#
#   Feature flags (MUST come before input file for validation):
#   --enable-simd: Enable SIMD operations (from our +simd128 rustflag)
#   --enable-bulk-memory: Enable bulk memory operations (memory.copy, memory.fill)
#   --enable-sign-ext: Enable sign extension operations (i32.extend16_s, etc.)
#   --enable-nontrapping-float-to-int: Enable saturating float-to-int conversions
#   --enable-mutable-globals: Enable mutable global imports/exports
#
# IMPORTANT: Feature flags must appear BEFORE the input file in the command line.
# wasm-opt validates the input file as it reads it, so features must be enabled
# before validation occurs. Otherwise you get "SIMD is disabled" errors.
#
# Note: -O3 produces slightly larger binaries than -Oz but with better runtime performance.
# For a portfolio demo, runtime performance is prioritized over binary size.
if command -v wasm-opt &> /dev/null; then
    echo "Optimizing with wasm-opt (-O3 for performance)..."
    BEFORE_SIZE=$(stat -c%s www/pkg/rource_wasm_bg.wasm 2>/dev/null || stat -f%z www/pkg/rource_wasm_bg.wasm)
    # Feature flags MUST come before input file to enable features during validation
    wasm-opt \
        --enable-simd \
        --enable-bulk-memory \
        --enable-sign-ext \
        --enable-nontrapping-float-to-int \
        --enable-mutable-globals \
        -O3 --converge --low-memory-unused \
        -o www/pkg/rource_wasm_bg_opt.wasm www/pkg/rource_wasm_bg.wasm
    mv www/pkg/rource_wasm_bg_opt.wasm www/pkg/rource_wasm_bg.wasm
    AFTER_SIZE=$(stat -c%s www/pkg/rource_wasm_bg.wasm 2>/dev/null || stat -f%z www/pkg/rource_wasm_bg.wasm)
    echo "  Before: $(numfmt --to=iec $BEFORE_SIZE 2>/dev/null || echo "$BEFORE_SIZE bytes")"
    echo "  After:  $(numfmt --to=iec $AFTER_SIZE 2>/dev/null || echo "$AFTER_SIZE bytes")"
    echo "WASM optimized for performance"
else
    echo "Note: wasm-opt not found (optional - install via binaryen for better performance)"
    echo "      Install with: apt-get install binaryen  OR  brew install binaryen"
fi

# Print output sizes
echo ""
echo "=== Build Complete ==="
echo ""
echo "Output files in: $WASM_DIR/www/pkg/"
ls -lh www/pkg/*.wasm www/pkg/*.js 2>/dev/null || true

# Print gzip size estimate and generate build-info.js
if command -v gzip &> /dev/null; then
    echo ""
    echo "Gzip sizes:"
    WASM_GZIP_KB=0
    for f in www/pkg/*.wasm; do
        if [ -f "$f" ]; then
            gzip_size=$(gzip -c "$f" | wc -c)
            WASM_GZIP_KB=$((gzip_size / 1024))
            echo "  $(basename "$f"): $(numfmt --to=iec $gzip_size 2>/dev/null || echo "$gzip_size bytes")"
        fi
    done

    # Generate build-info.js with actual sizes and stats
    JS_GZIP_SIZE=$(gzip -c www/pkg/rource_wasm.js 2>/dev/null | wc -c || echo 0)
    JS_GZIP_KB=$((JS_GZIP_SIZE / 1024))
    BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    CRATE_COUNT=$(ls -d "$PROJECT_ROOT/crates"/*/ 2>/dev/null | wc -l)

    # Test count - expensive to calculate, so we use a static value
    # Update manually by running: cargo test --all 2>&1 | grep -E "^test result:" | awk '{sum += $4} END {print sum}'
    TEST_COUNT=1821

    echo ""
    echo "Generating www/js/build-info.js..."
    cat > www/js/build-info.js << EOF
// Auto-generated by build-wasm.sh - do not edit manually
// Test count is static; update by running: cargo test --all 2>&1 | grep "^test result:" | awk '{sum += \$4} END {print sum}'
export const BUILD_INFO = {
    wasmGzipKB: ${WASM_GZIP_KB},
    jsGzipKB: ${JS_GZIP_KB},
    crateCount: ${CRATE_COUNT},
    testCount: ${TEST_COUNT},
    buildDate: '${BUILD_DATE}'
};
EOF
    echo "  WASM gzipped: ~${WASM_GZIP_KB}KB"
    echo "  Crates: ${CRATE_COUNT}"
fi

echo ""
echo "To serve the demo:"
echo "  cd $WASM_DIR/www && python3 -m http.server 8080"
echo "  Then open http://localhost:8080"
