#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Tom F <https://github.com/tomtom215>

# =============================================================================
# Update Test Counts
# =============================================================================
#
# This script runs the full test suite and extracts test counts per crate,
# storing them in metrics/test-counts.json as the single source of truth.
#
# Usage:
#   ./scripts/update-test-counts.sh          # Run tests and update counts
#   ./scripts/update-test-counts.sh --check  # Only display current counts
#   ./scripts/update-test-counts.sh --quick  # Quick parse without running tests
#
# Output:
#   - metrics/test-counts.json: Machine-readable test counts
#   - metrics/test-count.txt: Single total number
#   - metrics/test-count-display.txt: Display format (e.g., "2,100+")
#
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
METRICS_DIR="$PROJECT_ROOT/metrics"
COUNTS_FILE="$METRICS_DIR/test-counts.json"

# Ensure metrics directory exists
mkdir -p "$METRICS_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Check mode - just display current counts
if [[ "${1:-}" == "--check" ]]; then
    if [[ -f "$COUNTS_FILE" ]]; then
        echo -e "${BLUE}Current test counts from $COUNTS_FILE:${NC}"
        cat "$COUNTS_FILE"
        echo ""
        total=$(jq '.total' "$COUNTS_FILE" 2>/dev/null || echo "N/A")
        display=$(jq -r '.total_display' "$COUNTS_FILE" 2>/dev/null || echo "N/A")
        echo -e "${GREEN}Total tests: $total ($display)${NC}"
    else
        echo -e "${YELLOW}No test counts file found. Run without --check to generate.${NC}"
        exit 1
    fi
    exit 0
fi

echo -e "${BLUE}Running test suite to collect counts...${NC}"
echo ""

# Run tests and capture output
cd "$PROJECT_ROOT"
TEST_OUTPUT=$(cargo test --all 2>&1) || true

# Parse test counts
# Format: "test result: ok. X passed; Y failed; Z ignored; ..."
# We also track which crate the tests belong to from "Running" lines

declare -A crate_counts
declare -a crate_order
current_crate="other"

while IFS= read -r line; do
    # Match crate name from "Running unittests" or "Running tests/" line
    # Example: "Running unittests src/lib.rs (target/debug/deps/rource_math-abc123)"
    # Example: "Running tests/chaos_tests.rs (target/debug/deps/chaos_tests-abc123)"
    if [[ "$line" =~ Running.*\(target/debug/deps/([a-zA-Z0-9_]+)- ]]; then
        raw_crate="${BASH_REMATCH[1]}"
        # Normalize crate name (convert hyphens to underscores if needed)
        current_crate="${raw_crate//-/_}"

        # Track order for consistent output
        if [[ -z "${crate_counts[$current_crate]:-}" ]]; then
            crate_order+=("$current_crate")
            crate_counts[$current_crate]=0
        fi
    fi

    # Match test result line: "test result: ok. X passed; Y failed; Z ignored"
    if [[ "$line" =~ test\ result:.*\ ([0-9]+)\ passed ]]; then
        passed="${BASH_REMATCH[1]}"
        if [[ -n "${crate_counts[$current_crate]:-}" ]]; then
            # Accumulate counts (some crates have multiple test binaries)
            crate_counts[$current_crate]=$((crate_counts[$current_crate] + passed))
        else
            # Fallback for edge cases
            crate_order+=("$current_crate")
            crate_counts[$current_crate]=$passed
        fi
    fi
done <<< "$TEST_OUTPUT"

# Calculate total
total=0
for crate in "${crate_order[@]}"; do
    total=$((total + crate_counts[$crate]))
done

# Generate display format (floor to nearest 100)
display_floor=$(( (total / 100) * 100 ))
display_format="${display_floor}+"

# Map crate names to human-readable names and categorize
declare -A readable_names
readable_names["rource"]="rource-cli"
readable_names["rource_core"]="rource-core"
readable_names["rource_math"]="rource-math"
readable_names["rource_render"]="rource-render"
readable_names["rource_vcs"]="rource-vcs"
readable_names["rource_wasm"]="rource-wasm"
readable_names["chaos_tests"]="chaos-tests"
readable_names["load_tests"]="load-tests"
readable_names["proptests"]="proptests"
readable_names["visual_regression"]="visual-regression"

# Generate JSON output
{
    echo "{"
    echo "  \"_comment\": \"Auto-generated by scripts/update-test-counts.sh - DO NOT EDIT MANUALLY\","
    echo "  \"_updated\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\","
    echo "  \"total\": $total,"
    echo "  \"total_display\": \"$display_format\","
    echo "  \"crates\": {"

    first=true
    for crate in "${crate_order[@]}"; do
        if [[ "$first" == "true" ]]; then
            first=false
        else
            echo ","
        fi
        readable="${readable_names[$crate]:-$crate}"
        printf "    \"%s\": %d" "$readable" "${crate_counts[$crate]}"
    done
    echo ""
    echo "  }"
    echo "}"
} > "$COUNTS_FILE"

# Display summary
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}                    TEST COUNT SUMMARY                          ${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""

printf "%-25s %10s\n" "Crate" "Tests"
printf "%-25s %10s\n" "-------------------------" "----------"
for crate in "${crate_order[@]}"; do
    readable="${readable_names[$crate]:-$crate}"
    printf "%-25s %10d\n" "$readable" "${crate_counts[$crate]}"
done
printf "%-25s %10s\n" "-------------------------" "----------"
printf "%-25s %10d\n" "TOTAL" "$total"

echo ""
echo -e "${CYAN}Display format for docs: ${YELLOW}${display_format} tests${NC}"
echo ""
echo -e "${GREEN}Updated: $COUNTS_FILE${NC}"

# Also generate simple count files for easy reading/CI integration
echo "$total" > "$METRICS_DIR/test-count.txt"
echo "$display_format" > "$METRICS_DIR/test-count-display.txt"

echo -e "${GREEN}Updated: $METRICS_DIR/test-count.txt${NC}"
echo -e "${GREEN}Updated: $METRICS_DIR/test-count-display.txt${NC}"
echo ""
echo -e "${BLUE}To use in documentation: Reference 'metrics/test-count-display.txt' or use the value '$display_format'${NC}"
